name: Deploy Prefect flow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U prefectpip install prefect

      - name: Prefect Cloud login
        run: | 
          prefect config set PREFECT_API_KEY=${{secrets.PREFECT_API_KEY}} 
          prefect cloud workspace set --workspace "${{secrets.PREFECT_WORKSPACE}}"

      - name: Prefect deploy
        run: | 
          python hello_world.py
