name: Deploy Prefect flow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install prefect

      - name: Prefect Deploy
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: | 
          prefect cloud login --key ${{ secrets.PREFECT_API_KEY }} --workspace stack/default
          python hello_world.py
